# ThirdReality TRHub V3 - Amlogic A113D quad core 2GB RAM SoC, eMMC 32GB
BOARD_NAME="TRHub-V3"
BOARDFAMILY="jethub"
BOARD_MAINTAINER=""
BOOTCONFIG="trhub_v3_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
PACKAGE_LIST_BOARD="libubootenv-tool apparmor rfkill bluetooth bluez bluez-tools python3-pip watchdog python3-serial"
[[ "${RELEASE}" == "jammy" ]] || PACKAGE_LIST_BOARD="${PACKAGE_LIST_BOARD} util-linux-extra"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
# W155S1 uses custom drivers, no need to blacklist
MODULES_BLACKLIST=""
